#!/usr/bin/env python3
"""Build a single-file wanqm installer for a given router - the OPTIONAL scripted path.

The normal installation needs no Python at all: edit a config template, upload the
wanqm-*.rsc files and run /import INSTALL.rsc on the router (see the README). This
builder exists for people who want a one-file, token-injected installer instead: it
reads the SAME sources, substitutes secrets from secrets.local, and emits one .rsc
with everything embedded. Both paths install everything DISABLED and print (or, on a
re-import over an active install, re-run) the same enable commands.

Usage: python3 build_install.py [primary|backup|all]   (default: all)
  primary -> wanqm-install-primary.rsc  (the router that runs the orchestrator)
  backup  -> wanqm-install-backup.rsc   (orchestrator stays disabled - static priority)
"""
import pathlib
import re
import sys

D = pathlib.Path(__file__).parent
POLICY = "read,write,test,policy"

PROFILES = {
    "primary": {
        "outfile": "wanqm-install-primary.rsc",
        "config_body": "wanqm-config-primary.rsc",
    },
    "backup": {
        "outfile": "wanqm-install-backup.rsc",
        "config_body": "wanqm-config-backup.rsc",
    },
}


def esc(s: str) -> str:
    return (s.replace("\\", "\\\\")
             .replace('"', '\\"')
             .replace("$", "\\$")
             .replace("\n", "\\r\\n"))


def load_secrets() -> dict:
    """Read secrets.local (KEY=VALUE) and return a placeholder map.

    Secrets live ONLY there, so the *.rsc sources stay clean and can be shared safely.
    The generated wanqm-install-*.rsc DO contain the real values (they have to - they
    go onto the router), which is why the build sets them to chmod 600.
    """
    f = D / "secrets.local"
    if not f.exists():
        raise SystemExit(
            "ERROR: secrets.local is missing - without it the tokens would stay as "
            "placeholders and notifications would not work. Copy secrets.local.example "
            "to secrets.local and fill it in."
        )
    out = {}
    for line in f.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[f"__{k.strip()}__"] = v.strip()
    for req in ("__NOTIFY_TOKEN__", "__SMS_TOKEN__", "__SMS_TO__"):
        if req not in out:
            raise SystemExit(f"ERROR: secrets.local does not define {req.strip('_')}")
    return out


SECRETS = load_secrets()


def inject(body: str) -> str:
    for k, v in SECRETS.items():
        body = body.replace(k, v)
    return body


def cfg_str(body: str, name: str) -> str:
    """Read a `:global <name> "value"` string out of the config source."""
    m = re.search(r'^:global %s\s+"([^"]*)"' % re.escape(name), body, re.M)
    if not m:
        raise SystemExit(f"ERROR: the config file does not define {name}")
    return m.group(1)


def cfg_targets(body: str) -> list:
    """Read the `:global WanQmCfgTargets {...}` list out of the config source."""
    m = re.search(r'^:global WanQmCfgTargets\s*\{(.+?)\}', body, re.M)
    if not m:
        raise SystemExit("ERROR: the config file does not define WanQmCfgTargets")
    t = re.findall(r'"([^"]+)"', m.group(1))
    if len(t) != 4:
        raise SystemExit(f"ERROR: WanQmCfgTargets must hold exactly 4 targets, found {len(t)} "
                         "- the probe loop is unrolled, see the README")
    return t


SCRIPTS = ["wanqm-config", "wanqm-init", "wanqm-notify", "wanqm-probe",
           "wanqm-report", "wanqm-orchestrator", "wanqm-watchdog"]


def build(profile: str) -> None:
    p = PROFILES[profile]

    # The VRRP name, priorities and fuse behaviour all live in the config and in the
    # two wanqm-fuse-*.rsc sources - nothing about the setup is baked in here. The
    # builder only picks the fuse hosts (first two probe targets) and asserts that the
    # chosen profile matches the config's declared role.
    cfg_src = (D / p["config_body"]).read_text()
    role = cfg_str(cfg_src, "WanQmCfgRole")
    if role != profile:
        raise SystemExit(f"ERROR: {p['config_body']} declares WanQmCfgRole \"{role}\" "
                         f"but you are building the \"{profile}\" profile")
    fuse_hosts = tuple(cfg_targets(cfg_src)[:2])
    fuse_down = (D / "wanqm-fuse-down.rsc").read_text()
    fuse_up = (D / "wanqm-fuse-up.rsc").read_text()

    out = [f"# {p['outfile']} - generated by build_install.py (profile: {profile}); load with /import",
           "# Everything is installed DISABLED; a re-import over an ACTIVE install re-enables.",
           '# Remember the active state BEFORE the cleanup below wipes the schedulers:',
           ':local WanQmWasActive ([:len [/system scheduler find name="wanqm-probe" disabled=no]] > 0)',
           "# clean up the previous installation (idempotent)",
           '/system scheduler remove [find name~"^wanqm-"]',
           '/system script remove [find name~"^wanqm-"]',
           '/tool netwatch remove [find comment~"^wanqm-"]',
           ""]

    for name in SCRIPTS:
        body_file = p["config_body"] if name == "wanqm-config" else f"{name}.rsc"
        body = inject((D / body_file).read_text())
        # wanqm-config gets policy=read ONLY, and wanqm-notify read,write,test (no
        # `policy`): the netwatch fuse runs both directly, and a caller cannot run a
        # script whose policies exceed its own.
        policy = POLICY
        if name == "wanqm-config":
            policy = "read"
        if name == "wanqm-notify":
            policy = "read,write,test"
        out.append(f'/system script add name={name} policy={policy} '
                   f'comment="WAN Quality Monitor (wanqm)" source="{esc(body)}"')
        out.append("")

    orch_comment = ("wanqm: VRRP control (enable on the primary only)"
                    if role == "primary"
                    else "wanqm: VRRP control - KEEP DISABLED on the backup (static priority by design)")
    out += [
        "# schedulers (all disabled)",
        f'/system scheduler add name=wanqm-init-startup start-time=startup interval=0 disabled=yes '
        f'on-event="/system script run wanqm-init" policy={POLICY} '
        f'comment="wanqm: cold start after reboot"',
        f'/system scheduler add name=wanqm-probe interval=10s disabled=yes '
        f'on-event="/system script run wanqm-probe" policy={POLICY} '
        f'comment="wanqm: measurement+FSM"',
        f'/system scheduler add name=wanqm-report interval=5m disabled=yes '
        f'on-event="/system script run wanqm-report" policy={POLICY} '
        f'comment="wanqm: 5min report (calibration)"',
        f'/system scheduler add name=wanqm-watchdog interval=1m disabled=yes '
        f'on-event="/system script run wanqm-watchdog" policy={POLICY} '
        f'comment="wanqm: heartbeat freshness"',
        f'/system scheduler add name=wanqm-orchestrator interval=20s disabled=yes '
        f'on-event="/system script run wanqm-orchestrator" policy={POLICY} '
        f'comment="{orch_comment}"',
        "",
    ]

    h1, h2 = fuse_hosts
    out += [
        "# netwatch fuses (disabled; both entries share the same config-driven scripts)",
        f'/tool netwatch add comment=wanqm-fuse-1 host={h1} type=icmp interval=10s '
        f'packet-count=10 thr-loss-percent=80 disabled=yes '
        f'down-script="{esc(fuse_down)}" up-script="{esc(fuse_up)}"',
        f'/tool netwatch add comment=wanqm-fuse-2 host={h2} type=icmp interval=10s '
        f'packet-count=10 thr-loss-percent=80 disabled=yes '
        f'down-script="{esc(fuse_down)}" up-script="{esc(fuse_up)}"',
        "",
    ]

    if role == "primary":
        enable_sched = '/system scheduler enable [find name~"^wanqm-"]'
        enable_print = ':put "  /system scheduler enable [find name~\\"^wanqm-\\"]"'
    else:
        enable_sched = '/system scheduler enable [find name~"^wanqm-" name!="wanqm-orchestrator"]'
        enable_print = (':put "  /system scheduler enable '
                        '[find name~\\"^wanqm-\\" name!=\\"wanqm-orchestrator\\"]"')
    out += [
        "# initialize state (safe: UNKNOWN, no VRRP writes) + summary",
        "/system script run wanqm-init",
        f':put "[wanqm-install] OK  role={role}  (generated installer)"',
        f':log info "[wanqm] install OK role={role} (generated installer)"',
        ':put "SECURITY: this file carries your webhook tokens - remove it from the router now:"',
        ':put "  /file remove [find name~\\"(^|/)wanqm-install-.*\\\\.rsc\\$\\"]"',
        ':if ($WanQmWasActive) do={',
        '    :put "[wanqm-install] previous install was ACTIVE - re-enabling"',
        f'    {enable_sched}',
        '    /tool netwatch enable [find comment~"^wanqm-fuse-"]',
        '    :log info "[wanqm] install: re-enabled (was active)"',
        '} else={',
        '    :put "Everything is installed DISABLED. To activate:"',
        f'    {enable_print}',
        '    :put "  /tool netwatch enable [find comment~\\"^wanqm-fuse-\\"]"',
        '}',
        "",
    ]

    outfile = D / p["outfile"]
    outfile.write_text("\n".join(out))
    # The file carries the injected tokens, so keep it owner-only. chmod AFTER the write:
    # write_text() on an existing file leaves its mode alone, so a pre-existing 644 would
    # otherwise survive and silently expose the tokens.
    outfile.chmod(0o600)
    print(f"OK: {p['outfile']} ({len(outfile.read_text())} B, mode 600)")


targets = sys.argv[1:] or ["all"]
for t in (PROFILES.keys() if targets == ["all"] else targets):
    build(t)
